### ISSUE TITLE
[Question] How do you deal with inheritance

### ISSUE THREAD

**Issue by mantielero** [n0bra1n3r/cinterop#12]
I have the following inheritance tree:
![](https://dev.opencascade.org/doc/refman/html/class_b_rep_builder_a_p_i___modify_shape__inherit__graph.png)

where I have the following code:
```nim
csource "BRepBuilderAPI_Transform.hxx":
  type
    BRepBuilderAPI_Transform* = object of CClass

  converter toTopoDS_Shape*(self: BRepBuilderAPI_Transform):TopoDS_Shape {.importcpp:"(#)".}
```

How would you call a method from `BRepBuilderAPI_MakeShape` given than Nim doesn't have multiple inheritance?

**Comment by n0bra1n3r** [comment]
Multiple inheritance can be mimicked using converters + single inheritance + `cexpr^` in most cases. converters + single inheritance takes care of implicit conversion between related types, and `cexpr^` takes care of accessing inherited fields.

In the worst case scenario, you may have to write your own C++ to wrap functionality that can be translated to Nim via cinterop.

**Comment by mantielero** [comment]
Yes. I used `cexpr^` and it simply worked. Thanks.
