### ISSUE TITLE
No matching function for `SomeClass::SomeClass()`

### ISSUE THREAD

**Issue by mantielero** [n0bra1n3r/cinterop#13]
I am having an issue with the following:
```nim
csource "BRepBuilderAPI_Transform.hxx":
  type
    BRepBuilderAPI_Transform* = object of CClass

  converter toTopoDS_Shape*(self: BRepBuilderAPI_Transform):TopoDS_Shape {.importcpp:"(#)".}
```
The following fails:
```nim
var aBRepTrsf:BRepBuilderAPI_Transform = BRepBuilderAPI_Transform.init(aWire, aTrsf, false) 
```
with the C++ generated code:
```c++
N_LIB_PRIVATE BRepBuilderAPI_Transform aBRepTrsf__9c0qHVFq9cjuePb4cRv7GJPg;
...
aBRepTrsf__9c0qHVFq9cjuePb4cRv7GJPg = BRepBuilderAPI_Transform(aWire__78rPOEJid3gfRlRSPHyJ2A, aTrsf__mMdicb5vcYPa15dsHtfr9bg, NIM_FALSE);
```
where the first line is reported as an error:
```
error: no matching function for call to ‘BRepBuilderAPI_Transform::BRepBuilderAPI_Transform()’
  129 | N_LIB_PRIVATE BRepBuilderAPI_Transform aBRepTrsf__9c0qHVFq9cjuePb4cRv7GJPg;
```

On the other hand, the following works:
```nim
var aBRepTrsf:TopoDS_Shape = BRepBuilderAPI_Transform.init(aWire, aTrsf, false) 
```
with the generated C++ code:
```c++
N_LIB_PRIVATE TopoDS_Shape aBRepTrsf__9c0qHVFq9cjuePb4cRv7GJPg;
...
	aBRepTrsf__9c0qHVFq9cjuePb4cRv7GJPg = (BRepBuilderAPI_Transform(aWire__78rPOEJid3gfRlRSPHyJ2A, aTrsf__mMdicb5vcYPa15dsHtfr9bg, NIM_FALSE));
```
IMHO, both should work.

What am I missing?

**Comment by n0bra1n3r** [comment]
Looks like `BRepBuilderAPI_Transform` doesn't have a default C++ constructor (which is a constructor that accepts no parameters). Declarations like `BRepBuilderAPI_Transform someVariable;` is invalid in that case. You might need to figure out a way to initialize and/or pass around `BRepBuilderAPI_Transform` variables as references or pointers.

It seems weird though that `init` is generating that code. My `init` declaration uses the [`constructor` pragma](https://nim-lang.org/docs/manual.html#importcpp-pragma-wrapping-constructors), which should generate something like 
```cpp
BRepBuilderAPI_Transform aBRepTrsf__9c0qHVFq9cjuePb4cRv7GJPg(aWire__78rPOEJid3gfRlRSPHyJ2A, aTrsf__mMdicb5vcYPa15dsHtfr9bg, NIM_FALSE);
```
which should compile.

**Comment by n0bra1n3r** [comment]
[This](https://github.com/nim-lang/Nim/issues/6198#issuecomment-554184773) might be related to your problem. Are you calling `init` in the global scope? Generally it's a good idea to call all of your code from some sort of `main` function, as I've hit compiler bugs when invoking things in the global scope.

**Comment by mantielero** [comment]
Wow. Great catch. I could be there for ages! Thanks a lot.

**Comment by mantielero** [comment]
I think I am still having the problem.

From:
```nim
proc transform*[T:TopoDS_Shape ](s:T, trsf:gp_Trsf, copy:bool = false):BRepBuilderAPI_Transform =
  return BRepBuilderAPI_Transform.init(s.TopoDS_Shape, trsf, copy)
```
I get:
```c++
	BRepBuilderAPI_Transform result;
	nimfr_("transform", "/home/jose/src/occt.nim/experiments/lib/BRepBuilderAPI.nim");
{	nimln_(91, "/home/jose/src/occt.nim/experiments/lib/BRepBuilderAPI.nim");
	result = BRepBuilderAPI_Transform(s, (*trsf), copy);
```
With the error reported:
```bash
/home/jose/src/occt.nim/experiments/lib/nimcache/@mBRepBuilderAPI.nim.cpp: En la función ‘BRepBuilderAPI_Transform transform__gzH63J4pAMS1es9b2UnuwCA(TopoDS_Wire, gp_Trsf*, bool)’:
/home/jose/src/occt.nim/experiments/lib/nimcache/@mBRepBuilderAPI.nim.cpp:126:34: error: no matching function for call to ‘BRepBuilderAPI_Transform::BRepBuilderAPI_Transform()’
  126 |         BRepBuilderAPI_Transform result;
      |                                  ^~~~~~

```
> Note: `TopoDS_Wire`  inherites from `TodoDS_Shape`.

I am using `transform` from within a `main` function.

**Comment by n0bra1n3r** [comment]
You can probably solve this by calling the `init` directly instead of wrapping it with you own function, or use `importcpp` instead if you want to use your own functions:

```nim
proc transform*[T:TopoDS_Shape ](s:T, trsf:gp_Trsf, copy:bool = false):BRepBuilderAPI_Transform
  {.importcpp:"'0(@)".}
```

**Comment by n0bra1n3r** [comment]
Closing due inactivity.
