### ISSUE TITLE
`config.nims` is not correct 

### ISSUE THREAD

**Issue by mantielero** [n0bra1n3r/cinterop#19]
https://github.com/n0bra1n3r/cinterop/blob/6eb580d98296e4a1fe005ca24b2227a5dc44df8a/tests/config.nims#L1
I think it should be:
```
switch("path","../src")
```

**Comment by n0bra1n3r** [comment]
Thanks for the report. It is correct though, which is why the tests pass in the CI. [`--`](https://nim-lang.org/docs/nimscript.html#--.t%2Cuntyped%2Cuntyped) is an implicitly imported macro in Nimscript, but for some reason the vscode Nim plugin doesn't pick it up.

**Comment by mantielero** [comment]
I wasn't aware about `--` being a macro. One more thing a leart. Thanks.
