### ISSUE TITLE
[Question] Working with templates

### ISSUE THREAD

**Issue by mantielero** [n0bra1n3r/cinterop#2]
How should I work with templates?

I am trying to do [this](https://github.com/mantielero/occt.nim/blob/main/examples/bottle.nim#L18), but using your library. 

The type `Handle_Geom_TrimmedCurve` is defined [here](https://github.com/mantielero/occt.nim/blob/a10031d5f3f6277f9e442d1f8953d6c42d000607/src/Geom/geom_types.nim#L156):
```nim
Handle_Geom_TrimmedCurve* {.header: "Geom_TrimmedCurve.hxx", importcpp: "Handle_Geom_TrimmedCurve".} = Handle[Geom_TrimmedCurve]
```
 and `Handle` is defined [here](https://github.com/mantielero/occt.nim/blob/ee08fd55661a44152f93772c005ae6c55d6fdf8b/src/Standard/standard.nim#L241).

So how would I do that with **cinterop**?

What I am trying  to do is [here](https://github.com/mantielero/occt.nim/blob/main/src/lib/bottle.nim#L19) but I get an error about `init`.

**Comment by n0bra1n3r** [comment]
I'm interested in the error you're getting. This usecase should work, although I don't have a test with with a `importcpp`d type alias like yours. Everything is just `header` and `importcpp` pragmas under the hood, and there's nothing special about my `init` implementation (though the Nim C++ codegen has some bugs you might be hitting):

```nim
proc init*[T: CClass](Class: type[T]): T
  {.importcpp:"'*1(@)" varargs constructor.}
```

I can give you a similar example with templates that works in my codebase:

```nim
# diligent.nim

cnamespace Diligent: # C++ namespace
  csource &"{GraphicsTools}/MapHelper.hpp": # `GraphicsTools` is something like 'src/externals/DiligentEngine/DiligentTools/include'
    type MapHelper*[T] = object of CClass
```

```nim
# renderer.nim

...
var lightAttrs = MapHelper[LightAttribs].init(
    self.immediateContextRef,
    self.lightAttrBufferRef,
    cauto^MAP_TYPE.WRITE,
    cauto^MAP_FLAGS.DISCARD)
...
```
If you're getting weird errors that have `cpp` or `obj` files in them, it might be useful to look at the generated code in your nimcache folder.

I compile my project with the switch `--nimcache:nimcache` so the generated C++ is right inside my project folder and I can easily take a look at the code.

**Comment by mantielero** [comment]
I have the following code:
```nim
import occt

let
  myWidth = 50.0
  myThickness = 20.0
  myHeight = 70.0
  aPnt1 = newPnt(-myWidth / 2.0, 0, 0)
  aPnt2 = newPnt(-myWidth / 2.0, -myThickness / 4.0, 0)
  aPnt3 = newPnt(0, -myThickness / 2.0, 0)
  aPnt4 = newPnt(myWidth / 2.0, -myThickness / 4.0, 0)
  aPnt5 = newPnt(myWidth / 2.0, 0, 0)

echo aPnt2
echo aPnt3
echo aPnt4


#let aArcOfCircle = GC_MakeArcOfCircle.init()
let aArcOfCircle:Handle_Geom_TrimmedCurve = GC_MakeArcOfCircle.init(aPnt2,aPnt3,aPnt4)
```
and the last line is giving me the error:
```
Error: attempting to call undeclared routine: 'init'
```

The way in which I am defining `GC_MakeArcOfCircle` and `Handle_Geom_Trimmed_Curve`:
```nim
# Wrapping code
const libPath = "/usr/include/opencascade"

import cinterop
import std/os


csource libPath / "Standard_Handle.hxx":
  type
    handle*[T] = object of CClass


csource libPath / "Geom_TrimmedCurve.hxx":
  type
    Geom_TrimmedCurve* = object of CClass

csource libPath / "GC_MakeArcOfCircle.hxx":
  type 
    GC_MakeArcOfCircle* = object of CClass
    gp_Circ* = object of CClass
    

type
  Handle_Geom_TrimmedCurve* = handle[Geom_TrimmedCurve]
``` 
Where the headers look like this: [GC_MakeArcOfCircle.hxx](https://github.com/ceremcem/occt73/blob/master/inc/GC_MakeArcOfCircle.hxx#L62) and [Standard_Handle.hxx](https://github.com/ceremcem/occt73/blob/master/inc/Standard_Handle.hxx#L102).

**Comment by mantielero** [comment]
I think it was an stupid error. In order to have `init` available I need to import `cinterop`. 

I still have an issue, so I will close this issue an open a new one.
