### ISSUE TITLE
Qt interop?

### ISSUE THREAD

**Issue by matkuki** [n0bra1n3r/cinterop#26]
Hi @n0bra1n3r

This project is fantastic 👍👍👍 What are the possibilities to interface to Qt5/6 with it?
I don't have experience with `cinterop`, other that compiling the example, so would it be feasable to create an intermediate Qt C++ header/source pair of files and use them in `Nim`?

Thanks

**Comment by n0bra1n3r** [comment]
Thanks!

There is no special code that makes this work with specific libraries. This is a generic layer that allows Nim code to interact with existing C++ code without any "code generation" steps in between. So this project doesn't generate any header/source pairs. [This](https://nim-lang.org/docs/manual.html#implementation-specific-pragmas-importcpp-pragma) might help you understand what I mean.

Unless you have a specific example that shows how the C++ code in Qt can't be interfaced with via this project, I'm inclined to say that it should work with pretty much any C++ library. I'm already using it to interface with [Diligent Engine](https://github.com/DiligentGraphics/DiligentCore/tree/9cf3836c66442d64592576d128100773d69dea1a) which is a pretty massive C++ library, for example. I haven't used Qt though.

That being said, the overall effect of this project is that it moves the type checking from Nim to the C++ compiler that Nim invokes as part of the compilation process, so you will have to know a little bit of C++ to solve some corner cases.

**Comment by matkuki** [comment]
Ah, thanks for the detailed explanation 👍
Will try out a few experiments.
